### ISSUE TITLE
Suggest Edits button leads to 404

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#100]
The blue Suggest Edits button on webpages (like this https://www.hackshackers.com/groups/new-orleans/) goes to a 404. I think because they're linking to the hackshackers-hugo-content repo when we've changed to hackshackers/hackshackers-hugo

**Comment by ludstuen90** [comment]
Yep, that looks right to me - the idea is it should go here, no ? https://github.com/hackshackers/hackshackers-hugo/blob/master/content/groups/new-orleans.md

**Comment by ludstuen90** [comment]
Linked PR, based on above assumption https://github.com/hackshackers/hackshackers-hugo/pull/104

**Comment by samanthasunne** [comment]
Did you implement this change? If not please go ahead and do it
