### ISSUE TITLE
"Subscribe to events feed" leads to 404

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#101]
The "Subscribe to events feed" link, at the bottom of the global calendar, leads to a 404. The link is supposed to be https://www.hackshackers.com/lib/hackshackers.ical

**Comment by ludstuen90** [comment]
Hm, what is the link of the calendar? The one linked here is also leading to a 404 for me, and in a quick search I wasn't able to locate where the calendar should be. 

If you have any more information on where the calendar itself is hosted, I can keep investigating.

**Comment by joshkadis** [comment]
Hey Lucas, let’s connect soon and I can give you a tour of the site.
Josh@kadisco.com

**Comment by ludstuen90** [comment]
Update: Good news, I was able to finish my account activation with AWS. I called them, and they manually completed activation. 
I'm working now on getting access to the deployed components with Josh.

**Comment by ludstuen90** [comment]
Gained access to AWS. This issue is dependent on how we resolve the events on the homepage: https://github.com/hackshackers/hackshackers-hugo/issues/99

**Comment by ludstuen90** [comment]
Subscribe should also be fixed, leading to a place where users can import the ical file into their calendar system of choice. Assigning to @samanthasunne  to close if all looks good.
