### ISSUE TITLE
Hide but don't delete misinformation-grants from /resources

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#102]

**Comment by ludstuen90** [comment]
Hey there, just confirming: 
- It sounds like we want this link to disappear, is that right?: 
![image](https://user-images.githubusercontent.com/6817579/110225010-caba6a80-7ebf-11eb-8672-9949e8d57188.png)
- Do we also want the page itself to disappear, if a user attempts to access it but has it bookmarked? 
- Do we want this to be able to be easily re-enabled?

**Comment by samanthasunne** [comment]
Yes to all three? :-) Let me know if there are complications and I can compromise.

**Comment by ludstuen90** [comment]
This is perfect, this is the easiest of all possible combinations! I will send a PR right over.
