### ISSUE TITLE
Dependabot pull requests

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#108]
Dependabot is always filing PRs... do we need an admin on this repo to approve them? Should we simply approve any dependabot PR that comes in?

**Comment by joshkadis** [comment]
Those can almost always be ignored but should be reviewed by an admin. Merging the PR would trigger a rebuild/redeployment of the site, but it wouldn't actually have an effect. Someone would need to run [this command](https://github.com/hackshackers/hackshackers-hugo/blob/master/themes/hackshackers-2017/package.json#L5), commit the resulting bundle, then trigger a deployment in order for the change to take effect.

**Comment by samanthasunne** [comment]
If we don't need to merge, and can safely ignore, I suggest we ignore them...

Are we even using dependabot anymore? I thought we dropped it.

**Comment by ludstuen90** [comment]
Sounds good. I can keep an eye on these as they are created, and merge them in when appropriate.
I'll give priority to anything that comes up affecting compatibility or security.
