### ISSUE TITLE
Search popup stays up on search results page

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#109]
If you click the little search icon in the nav bar, it pops up a black background where you type in your search term. If you do this while on a search results page, the pop up doesn't go away, even if you press enter or click out of it. You have to click the search icon in the nav bar again to make it go away.

**Comment by ludstuen90** [comment]
Got it -- summarizing, the change we want are: 
- If on the search results page, when executing a search, the search popup should disappear to show updated results.
- If a user cicks roughly below the white line (added for visualization), the search popup should disappear 
![image](https://user-images.githubusercontent.com/6817579/112737730-5fead500-8f3b-11eb-9350-f96167b73f38.png)
- While the search pop-up is open, if a user presses escape, the search popup should disappear. 
- Similarly, clicking on the search icon while the popup is open will cause the window to close.

**Comment by samanthasunne** [comment]
Yes, and additionally, while the search pop-up is open, if a user presses enter, the search popup should disappear

**Comment by ludstuen90** [comment]
- [ ] If on the search results page, when executing a search, the search popup should disappear to show updated results.
- [ ] If a user clicks roughly below the white line (added for visualization), the search popup should disappear
- [ ] While the search pop-up is open, if a user presses escape, the search popup should disappear.
- [ ] Similarly, clicking on the search icon while the popup is open will cause the window to close.
- [ ] Yes, and additionally, while the search pop-up is open, if a user presses enter, the search popup should disappear

**Comment by ludstuen90** [comment]
Ready for review @samanthasunne

**Comment by samanthasunne** [comment]
Done - search popup disappears when users presses Enter or clicks out of it
