### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by samanthasunne** [hackshackers/hackshackers-hugo#98]
Search just says "Loading search database..."

https://www.hackshackers.com/search/#test%20test

**Comment by ludstuen90** [comment]
Linked pull request https://github.com/hackshackers/hackshackers-hugo/pull/105

**Comment by samanthasunne** [comment]
I tested it just now (Opera and desktop) and it still said "Loading search database..." indefinitely.

**Comment by ludstuen90** [comment]
Hmm, it looks like it is now working on mobile. Did you clear the cache? Also, it takes a few seconds for the DB to populate, I wonder if it is that 
![Screenshot_20210309-205050_Chrome](https://user-images.githubusercontent.com/6817579/110554427-8c1fec80-8119-11eb-96d4-22ca1ebbc6e7.jpg)

**Comment by samanthasunne** [comment]
Tried again and it works!
